echo DYAD_INSTALL_PREFIX=${DYAD_INSTALL_PREFIX}
echo DYAD_KVS_NAMESPACE=${DYAD_KVS_NAMESPACE}
echo DYAD_DTL_MODE=${DYAD_DTL_MODE}
echo DYAD_PATH_PRODUCER=${DYAD_PATH_PRODUCER}
echo DYAD_PATH_CONSUMER=${DYAD_PATH_CONSUMER}
